### ISSUE TITLE
说明：所有 Section 的顺序

### ISSUE THREAD

**Issue by sykp241095** [sykp241095/gantt-viewer-for-github-project#11]
顺序如下：

- Search Section：
- Panel List Section：当 Panel 数量小于 5 时，整个 Panel List 变高，高度为 Panel 高度 x Panel 数量，当数量大于 5 时，为定高可滚动。取消现在的根据历史显示的功能，按顺序展示就好。
- Helper Section，包含：
  - Guess，默认不可点击，只有识别出 repo 来才可以点击
  - Set Time，默认不可点击，只有识别出 issue 详情页才可以点击
- Option Section，包含（按顺序）：
  - Manage Panels
  - User Guide
  - Reset Access Token
- User Info Section

**Comment by wd0517** [comment]
已更新
